name: Check AWS Amplify PR Preview Link

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-preview-link:
    runs-on: ubuntu-latest

    steps:
      - name: Get Amplify preview URL from comment
        id: get-preview-url
        uses: actions/github-script@v6
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // Look for the comment from "aws-amplify" with the specific URL format
            const amplifyComment = comments.find(comment => 
              comment.user.login.startsWith("aws-amplify") &&
              comment.body.includes("Access this pull request here:")
            );

            if (!amplifyComment) {
              core.setFailed("No Amplify preview URL found in comments.");
              return;
            }

            // Extract the URL from the comment
            const urlMatch = amplifyComment.body.match(/https?:\/\/[^\s]+/);
            if (!urlMatch) {
              core.setFailed("Amplify preview URL not found in the comment.");
              return;
            }

            // Set the URL as an output variable
            core.setOutput("preview_url", urlMatch[0]);
            core.setOutput("comment_id", amplifyComment.id);

      - name: Wait for preview link to become active
        id: wait-for-link
        run: |
          PREVIEW_URL="${{ steps.get-preview-url.outputs.preview_url }}"
          MAX_ATTEMPTS=20  # Max number of attempts
          SLEEP_INTERVAL=30  # Seconds between checks
          ATTEMPTS=0

          while [ "$ATTEMPTS" -lt "$MAX_ATTEMPTS" ]; do
            HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" $PREVIEW_URL)

            if [ "$HTTP_STATUS" -eq "200" ]; then
              echo "::set-output name=link_status::active"
              exit 0
            fi

            # Increment the attempt counter
            ATTEMPTS=$((ATTEMPTS + 1))
            echo "Attempt $ATTEMPTS: Preview link not active yet, waiting..."

            # Wait for the next interval before checking again
            sleep $SLEEP_INTERVAL
          done

          # If loop exits, link is still broken after max attempts
          echo "::set-output name=link_status::broken"

      - name: Delete or notify if preview link is broken
        uses: actions/github-script@v6
        if: steps.wait-for-link.outputs.link_status == 'broken'
        with:
          script: |
            const commentId = ${{ steps.get-preview-url.outputs.comment_id }};

            // Delete the original comment if the link is broken
            if (commentId) {
              await github.rest.issues.deleteComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: commentId,
              });
            }

            // Post a new comment indicating the broken link
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "⚠️ The AWS Amplify PR preview link is broken and not accessible.",
            });
