name: Check AWS Amplify PR Preview Link

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-preview-link:
    runs-on: ubuntu-latest

    steps:
      - name: Wait before proceeding
        run: |
          echo "Waiting for 1 minute and 30 seconds before checking the preview link..."
          sleep 90

      - name: Get Amplify preview URL from comment
        id: get-preview-url
        uses: actions/github-script@v6
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // Find the comment from "aws-amplify" containing the preview link
            const amplifyComment = comments.find(comment => 
              comment.user.login.startsWith("aws-amplify") &&
              comment.body.includes("Access this pull request here:")
            );

            if (!amplifyComment) {
              core.setFailed("No Amplify preview URL found in comments.");
              return;
            }

            // Extract the URL from the comment
            const urlMatch = amplifyComment.body.match(/https?:\/\/[^\s]+/);
            if (!urlMatch) {
              core.setFailed("Amplify preview URL not found in the comment.");
              return;
            }

            // Set the URL and comment ID as output variables
            core.setOutput("preview_url", urlMatch[0]);
            core.setOutput("comment_id", amplifyComment.id);

      - name: Check if preview link is reachable
        id: check-link
        run: |
          PREVIEW_URL="${{ steps.get-preview-url.outputs.preview_url }}"
          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" $PREVIEW_URL)

          if [ "$HTTP_STATUS" -eq "200" ]; then
            echo "::set-output name=link_status::active"
          else
            echo "::set-output name=link_status::broken"
          fi

      - name: Delete or notify if preview link is broken
        uses: actions/github-script@v6
        if: steps.check-link.outputs.link_status == 'broken'
        with:
          github-token: ${{ secrets.PAT_TOKEN }}  # Use the PAT instead of default GITHUB_TOKEN
          script: |
            const commentId = ${{ steps.get-preview-url.outputs.comment_id }};

            // Delete the original Amplify comment if the link is broken
            if (commentId) {
              await github.rest.issues.deleteComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: commentId,
              });
            }
